//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Edu06.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Edu06.Core.Resources.Content", typeof(Content).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID của tổ hợp môn không được trống !.
        /// </summary>
        public static string E_DepartmentIDNotEmpty {
            get {
                return ResourceManager.GetString("E_DepartmentIDNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID của tổ hợp môn không tìm thấy trong các tổ hợp môn !.
        /// </summary>
        public static string E_DepartmentIDNotFound {
            get {
                return ResourceManager.GetString("E_DepartmentIDNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tổ hợp môn không được trùng nhau !.
        /// </summary>
        public static string E_DepartmentNameNotDuplicate {
            get {
                return ResourceManager.GetString("E_DepartmentNameNotDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tổ hợp môn không được trống !.
        /// </summary>
        public static string E_DepartmentNameNotEmpty {
            get {
                return ResourceManager.GetString("E_DepartmentNameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên môn học không được phép trùng nhau !.
        /// </summary>
        public static string E_SubjectNameNotDuplicate {
            get {
                return ResourceManager.GetString("E_SubjectNameNotDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên môn học không được phép trống !.
        /// </summary>
        public static string E_SubjectNameNotEmpty {
            get {
                return ResourceManager.GetString("E_SubjectNameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã giáo viên không được phép để trùng nhau !.
        /// </summary>
        public static string E_TeacherCodeNotDuplicate {
            get {
                return ResourceManager.GetString("E_TeacherCodeNotDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã giáo viên không được phép để trống !.
        /// </summary>
        public static string E_TeacherCodeNotEmpty {
            get {
                return ResourceManager.GetString("E_TeacherCodeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên giáo viên không được phép để trống !.
        /// </summary>
        public static string E_TeacherNameNotEmpty {
            get {
                return ResourceManager.GetString("E_TeacherNameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm thành công !.
        /// </summary>
        public static string S_PostContent {
            get {
                return ResourceManager.GetString("S_PostContent", resourceCulture);
            }
        }
    }
}
